#
# example ported from json config
#

# version = "0.6.0-100"

[webservice]
scheme = "http"
host = "0.0.0.0"
port = 9090

  [[webservice.headers]]

[[clients]]
location = "cottage"
ip = "10.0.1.197"
port = 2030
active = true

[[clients]]
location = "shed"
ip = "10.0.1.115"
port = 2030
active = false

[[temperature.locations]]
client = "cottage"

  [[temperature.locations.probes]]
  sensor = 0
  location = "cottage-south"

  [[temperature.locations.probes]]
  sensor = 1
  location = "cottage-east"

[[temperature.locations]]
client = "shed"

  [[temperature.locations.probes]]
  sensor = 0
  location = "shed-inside"

  [[temperature.locations.probes]]
  sensor = 1
  location = "shed-west"

